### ISSUE TITLE
Strange upstream dep on tslib

### ISSUE THREAD

**Issue by yankeeinlondon** [cartant/firebase-key#15]
I can see that you're only using tslib as a devDep (which of course makes sense) but I run into problems upstream as a consumer when trying to:

- tree-shake a dependency tree with rollup (it says firebase-key needs it)
- do a larger grain "module-shake" for some microservices and exclude ts-lib but include firebase-key

Can you think of any reason why this could be happening?

**Comment by cartant** [comment]
I've published 2.0.1 and I've removed `tslib` from the the dependencies and from the TypeScript configuration.

It wasn't really required, as the amount of boilerplate generated was very small and only in `dist/index.js` and `dist/key.js`. Also, ES2015 code is included in the distribution now for anyone who wants to use it.

And it should have been a `dependency`, rather than a `devDependency`.

Using it did effect two requires. One in `dist/index.js` and the other in `dist/key.js` - as it was used for the re-exports. It wasn't required in the files in the `esm5` directory - which is pointed to by the `module` entry point in the `package.json`. My understanding is that Rollup would have used the `module` entry point, so I'm not sure why it would have been concerned with `tslib`. Anyway, it has been removed.
